#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Commands\BuildCommand;
use Symfony\Component\Console\Application;

$root = __DIR__;

$application = new Application('Encyclopedia', '0.1.0');

$application->addCommands([
    new BuildCommand($root),
]);

$application->run();
